"""Add owner_id to plants table

Revision ID: 7431bed65078
Revises: 1f0a023e2270
Create Date: 2025-03-11 17:16:54.575509

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7431bed65078'
down_revision = '1f0a023e2270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'plant', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plant', type_='foreignkey')
    op.drop_column('plant', 'owner_id')
    # ### end Alembic commands ###
