"""Add life_cycle field to Plant model

Revision ID: cf089a731f73
Revises: 9e2b96a9f76b
Create Date: 2025-04-24 21:27:14.622238

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cf089a731f73'
down_revision = '9e2b96a9f76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('life_cycle', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'life_cycle')
    # ### end Alembic commands ###
